name: CI

on:
  push:
    branches:
        - '*'

jobs:
  CI:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install and setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'
    - name: Run tests
      run: dotnet test
    - name: Build Rider and ReSharper plugin
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildPlugin